# Generated by Django 4.1.7 on 2023-03-10 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='flow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='app.flow', verbose_name='Поток'),
            preserve_default=False,
        ),
    ]
